# Generated by Django 5.2.7 on 2025-10-17 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='short',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AddField(
            model_name='short',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 17, 16, 11, 14, 800005, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='short',
            name='content',
            field=models.FileField(upload_to='Post/{USER}/'),
        ),
    ]
