# Generated by Django 5.2.7 on 2025-10-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0002_alter_short_options_short_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
