# Generated by Django 5.2.7 on 2025-10-17 16:44

import short.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='content',
            field=models.FileField(upload_to=short.models.user_dir),
        ),
    ]
