# Generated by Django 5.2.7 on 2025-10-14 15:48

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
