# Generated by Django 5.2.7 on 2025-10-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='m7md1m79vwmmemcgbmpb'),
        ),
    ]
